export const products = [
    {
      id: "prod-1",
      modelo: "Laptop Dell Inspiron 15",
      descripcion:
        "Laptop potente con procesador Intel Core i7 y pantalla Full HD",
      precio: 899.99,
      marca: "Dell",
      stock: 20,
      imagen:
        "https://plazavea.vteximg.com.br/arquivos/ids/28686194-1000-1000/image-474ff794f1bc4d6cb8c5f3c87e35cdc6.jpg",
      categoria: {
        id: "CAT-lap-d87JGK",
        nombre: "Laptops",
        descripcion: "Computadoras portátiles",
        imagen: "laptops.jpg",
      },
      fichaTecnica: {
        procesador: "Intel Core i7",
        memoriaRAM: "8 GB DDR4",
        almacenamiento: "512 GB SSD",
        pantalla: "15.6 pulgadas Full HD",
        sistemaOperativo: "Windows 10 Home",
      },
    },
    {
      id: "prod-2",
      modelo: "Monitor LG UltraWide 34UC98",
      descripcion:
        "Monitor ultra panorámico con resolución QHD y tecnología FreeSync",
      precio: 699.99,
      marca: "LG",
      stock: 15,
      imagen:
        "https://falabella.scene7.com/is/image/FalabellaPE/gsc_127016858_4777793_1?wid=1500&hei=1500&qlt=70",
      categoria: {
        id: "CAT-mon-f89KLM",
        nombre: "Monitores",
        descripcion: "Pantallas de visualización",
        imagen: "monitores.jpg",
      },
      fichaTecnica: {
        tamaño: "34 pulgadas",
        resolucion: "3440x1440 QHD",
        tipoPanel: "IPS",
        frecuenciaRefresco: "75Hz",
        tecnologia: "FreeSync",
      },
    },
    {
      id: "prod-3",
      modelo: "Mouse Logitech MX Master 3",
      descripcion: "Mouse ergonómico avanzado con seguimiento de alta precisión",
      precio: 99.99,
      marca: "Logitech",
      stock: 30,
      imagen:
        "https://www.yamoshi.com.pe/21624-large_default/mouse-wireless-logitech-mx-master-3s-910-006561-graphite.jpg",
      categoria: {
        id: "CAT-per-i9JHKL",
        nombre: "Periféricos",
        descripcion: "Dispositivos auxiliares",
        imagen: "perifericos.jpg",
      },
      fichaTecnica: {
        tipo: "Inalámbrico",
        conexion: "Bluetooth/USB",
        sensor: "Darkfield Laser",
        botones: "7 botones programables",
      },
    },
    {
      id: "prod-4",
      modelo: "Router ASUS RT-AX86U",
      descripcion: "Router WiFi 6 de alta velocidad para juegos y streaming",
      precio: 249.99,
      marca: "ASUS",
      stock: 25,
      imagen:
        "https://dlcdnwebimgs.asus.com/gain/55ce4cd4-b7f9-4bf6-854b-fdc567958f4c/w692",
      categoria: {
        id: "CAT-red-u76HJK",
        nombre: "Redes",
        descripcion: "Dispositivos de conexión en red",
        imagen: "redes.jpg",
      },
      fichaTecnica: {
        estandar: "WiFi 6 (802.11ax)",
        velocidad: "AX5700",
        puertosLAN: "4x Gigabit",
        puertosWAN: "1x Gigabit",
        antenas: "4 antenas externas",
      },
    },
    {
      id: "prod-5",
      modelo: "Teclado mecánico Corsair K95 RGB Platinum XT",
      descripcion:
        "Teclado mecánico premium con retroiluminación RGB y teclas programables",
      precio: 199.99,
      marca: "Corsair",
      stock: 20,
      imagen:
        "https://oechsle.vteximg.com.br/arquivos/ids/2960421-1000-1000/image-c28045e99e9b45d3b885ca7fbfd71d93.jpg?v=637495671564070000",
      categoria: {
        id: "CAT-per-i9JHKL",
        nombre: "Periféricos",
        descripcion: "Dispositivos auxiliares",
        imagen: "perifericos.jpg",
      },
      fichaTecnica: {
        tipo: "Mecánico",
        tecnologia: "CHERRY MX",
        retroiluminacion: "RGB",
        teclasProgramables: "6 teclas G programables",
      },
    },
    {
      id: "prod-6",
      modelo: "Impresora multifuncional HP OfficeJet Pro 9025",
      descripcion:
        "Impresora multifuncional con conectividad WiFi y impresión dúplex automática",
      precio: 299.99,
      marca: "HP",
      stock: 15,
      imagen:
        "https://falabella.scene7.com/is/image/FalabellaPE/gsc_122367361_3337106_1?wid=1500&hei=1500&qlt=70",
      categoria: {
        id: "CAT-imp-d90UIO",
        nombre: "Impresoras",
        descripcion: "Dispositivos de impresión",
        imagen: "impresoras.jpg",
      },
      fichaTecnica: {
        funciones: "Impresión, copia, escaneo, fax",
        conectividad: "WiFi, Ethernet, USB",
        velocidadImpresion: "Hasta 24 ppm (negro/color)",
        impresionDúplex: "Automática",
      },
    },
    {
      id:"prod-7",
      modelo: "Tarjeta gráfica NVIDIA GeForce RTX 3080",
      descripcion:
        "Tarjeta gráfica de última generación para gaming de alta gama",
      precio: 799.99,
      marca: "NVIDIA",
      stock: 10,
      imagen:
        "https://ripleype.imgix.net/https%3A%2F%2Fmedia-prod-use-1.mirakl.net%2FSOURCE%2Fd4e87b49331141338a827d24475ef220?w=750&h=555&ch=Width&auto=format&cs=strip&bg=FFFFFF&q=60&trimcolor=FFFFFF&trim=color&fit=fillmax&ixlib=js-1.1.0&s=15ea7857b29247eda6562d58dc355be1",
      categoria: {
        id: "CAT-com-g78OPQ",
        nombre: "Componentes",
        descripcion: "Piezas y componentes de computadora",
        imagen: "componentes.jpg",
      },
      fichaTecnica: {
        arquitectura: "NVIDIA Ampere",
        memoria: "10 GB GDDR6X",
        interfaz: "PCI Express 4.0",
        salidasVideo: "3x DisplayPort, 1x HDMI",
      },
    },
    {
      id: "prod-8",
      modelo: "Laptop Dell XPS 15",
      descripcion: "Laptop potente con pantalla táctil y diseño elegante",
      precio: 1599.99,
      marca: "Dell",
      stock: 20,
      imagen: "https://m.media-amazon.com/images/I/91WgL3IbNIL._AC_SL1500_.jpg",
      categoria: {
        id: "CAT-lap-uE8rKP",
        nombre: "Laptops",
        descripcion: "Categoría de computadoras portátiles",
        imagen: "laptops.jpg",
      },
      fichaTecnica: {
        pantalla: "15.6 pulgadas 4K UHD",
        procesador: "Intel Core i7 de décima generación",
        memoriaRAM: "16 GB DDR4",
        almacenamiento: "512 GB SSD",
        tarjetaGrafica: "NVIDIA GeForce GTX 1650 Ti",
      },
    },
    {
      id: "prod-9",
      modelo: "Monitor Gaming ASUS ROG Swift PG279Q",
      descripcion: "Monitor gaming de alta gama con tasa de refresco de 144Hz",
      precio: 699.99,
      marca: "ASUS",
      stock: 15,
      imagen:
        "https://dlcdnwebimgs.asus.com/gain/42BD1450-5437-42FD-8F5B-1777841C8EC3/w717/h525",
      categoria: {
        id: "CAT-mon-0AvbKb",
        nombre: "Monitores",
        descripcion: "Categoría de monitores de computadora",
        imagen: "monitores.jpg",
      },
      fichaTecnica: {
        tamaño: "27 pulgadas",
        resolucion: "2560 x 1440 píxeles",
        tecnologiaPanel: "IPS",
        conectividad: "HDMI, DisplayPort, USB 3.0",
        frecuenciaRefresco: "144Hz",
        respuesta: "4ms",
      },
    },
    {
      id: "prod-10",
      modelo: "Laptop ASUS ZenBook 14",
      descripcion: "Laptop ultradelgada y ligera para trabajo y entretenimiento",
      precio: 1099.99,
      marca: "ASUS",
      stock: 20,
      imagen: "https://dlcdnwebimgs.asus.com/gain/29536fe3-8fd7-4153-88f2-d4203fc4f084/",
      categoria: {
        id: "CAT-lap-jD9IWP",
        nombre: "Laptops",
        descripcion: "Categoría de computadoras portátiles",
        imagen: "laptops.jpg",
      },
      fichaTecnica: {
        procesador: "Intel Core i7-1165G7",
        memoriaRAM: "16 GB DDR4",
        almacenamiento: "512 GB SSD",
        pantalla: "Full HD LED 14 pulgadas",
        graficos: "Intel Iris Xe Graphics",
      },
    },
    {
      id: "prod-11",
      modelo: "Monitor LG UltraGear 27GL850-B",
      descripcion:
        "Monitor gaming con alta frecuencia de actualización y tiempo de respuesta rápido",
      precio: 499.99,
      marca: "LG",
      stock: 15,
      imagen:
        "https://www.pcfactory.com.pe/public/foto/2611/1_1000.jpg?t=1710359998959",
      categoria: {
        id: "CAT-mon-Pj3KlR",
        nombre: "Monitores",
        descripcion: "Categoría de monitores para computadoras",
        imagen: "monitores.jpg",
      },
      fichaTecnica: {
        tipoPanel: "Nano IPS",
        resolucion: "2560 x 1440 QHD",
        tasaRefresco: "144Hz (Overclocking 160Hz)",
        tiempoRespuesta: "1ms (GtG)",
        conectividad: "HDMI, DisplayPort, USB",
      },
    },
    {
      id: "prod-12",
      modelo: "Impresora HP LaserJet Pro MFP M28w",
      descripcion: "Impresora multifuncional compacta para hogar y oficina",
      precio: 149.99,
      marca: "HP",
      stock: 25,
      imagen: "https://www.hp.com/es-es/shop/Html/Merch/Images/c07836222_1750x1285.jpg",
      categoria: {
        id: "CAT-imp-BvE9w2",
        nombre: "Impresoras",
        descripcion: "Categoría de impresoras para diversos usos",
        imagen: "impresoras.jpg",
      },
      fichaTecnica: {
        tipoImpresion: "Láser",
        funciones: "Impresión, escaneo, copiado",
        velocidadImpresion: "Hasta 18 ppm",
        conectividad: "Wi-Fi, USB 2.0",
      },
    },
    {
      id: "prod-13",
      modelo: "Mouse inalámbrico Logitech MX Master 3",
      descripcion: "Mouse ergonómico avanzado para productividad y creatividad",
      precio: 99.99,
      marca: "Logitech",
      stock: 30,
      imagen: "https://plazavea.vteximg.com.br/arquivos/ids/9149085-1000-1000/imageUrl_2.jpg",
      categoria: {
        id: "CAT-per-fE2kR8",
        nombre: "Periféricos",
        descripcion: "Categoría de dispositivos periféricos para computadoras",
        imagen: "perifericos.jpg",
      },
      fichaTecnica: {
        tipoConexion: "Bluetooth, USB-C",
        botones: "7 botones personalizables",
        sensor: "Darkfield de 4000 DPI",
        bateria: "Recargable vía USB-C, hasta 70 días de duración",
      },
    },
    {
      id: "prod-14",
      modelo: "Router ASUS RT-AX86U",
      descripcion:
        "Router Wi-Fi 6 de alta velocidad y rendimiento para hogares y oficinas",
      precio: 199.99,
      marca: "ASUS",
      stock: 20,
      imagen: "https://http2.mlstatic.com/D_NQ_NP_959051-MPE72507548185_102023-O.webp",
      categoria: {
        id: "CAT-red-Kj6Pw3",
        nombre: "Redes",
        descripcion: "Categoría de dispositivos de red para conexiones",
        imagen: "redes.jpg",
      },
      fichaTecnica: {
        estandarWifi: "Wi-Fi 6 (802.11ax)",
        velocidadMaxima: "AX5700 (4804 Mbps en 5 GHz, 861 Mbps en 2.4 GHz)",
        puertos: "4 x Gigabit LAN, 1 x Gigabit WAN, 2 x USB 3.2",
        caracteristicas: "AiMesh, AiProtection Pro, WTFast, QoS adaptable",
      },
    },
  ];